[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_anchor = "8NWgWiLoXdERkez5eb5zBjDSTu9dSHrbLyTx4tKnJGzy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aadhi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
